import { ISkill } from '../models/ISkill';

export const SKILLS_LIST: ISkill[] = [
    { name: 'Angular', level: 3 },
    { name: 'AngularJS', level: 3 },
    { name: 'JavaScript', level: 3 },
    { name: 'TypeScript', level: 3 },
    { name: 'RxJS', level: 3 },
    { name: 'PrimeNG', level: 3 },
    { name: 'Swagger', level: 3 },
    { name: 'NGRX', level: 3 },
    { name: 'Chart.JS', level: 2 },
    { name: 'Floating UI', level: 2 },
    { name: 'Popper', level: 2 },
    { name: 'Chart.JS', level: 2 },
    { name: 'HTML5', level: 2 },
    { name: 'SCSS/CSS', level: 2 },
    { name: 'Git', level: 2 },
    { name: 'Quill', level: 2 },
    { name: 'BEM', level: 2 },
    { name: 'REST API', level: 2 },
    { name: 'Grunt', level: 2 },
    { name: 'Webpack', level: 2 },
    { name: 'Vite', level: 2 },
    { name: 'NX', level: 1 },
    { name: 'Bun', level: 1 },
    { name: 'Elysia', level: 1 },
    { name: 'JQuery', level: 1 },
    { name: 'AOS', level: 1 },
    { name: 'Docker', level: 1 },
    { name: 'Nginx', level: 1 },
    { name: 'CI/CD', level: 1 },
    { name: 'Github Actions', level: 1 },
    { name: 'ESLint', level: 1 },
    { name: 'Storybook' },
    { name: 'Jira' },
    { name: 'Yougile' },
    { name: 'Trello' },
    { name: 'Scrum' },
    { name: 'Kanban' },
    { name: 'AGILE' },
    { name: 'SAFe' },
] as const;
